name             'awscli'
maintainer       'Mischa Taylor'
maintainer_email 'mischa@misheska.com'
license          'Apache 2.0'
description      'Installs/Configures awscli'
long_description 'Installs/Configures awscli'
version          '0.1.0'
